name = "client-portal"
main = "worker-v2.js" # Updated to v2 with proper API surface
compatibility_date = "2024-09-23"

[env.production]
name = "client-portal-prod"

# Environment variables (set these in Cloudflare dashboard)
# SUPABASE_URL = "https://vwqkhjnkummwtvfxgqml.supabase.co"
# SUPABASE_ANON_KEY = "sb_publishable_I7JH7fI8hWP1AtGKskpWew_E4ws1YDa"
# SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cWtoam5rdW1td3R2ZnhncW1sIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjAwMzA0OSwiZXhwIjoyMDcxNTc5MDQ5fQ.IonJfbD_34jImKfPIfdEwUHPhLx0bnMRniq2wJ3Uqmc"
# JWT_SECRET = "uOQbRSkJPy2L6fYKRPAPa+pMYZwKKZaoDMXVyc7nCFH4cQsN+VDqFsxx6fcc2ljXp98bT1Lk558YZGHp6+N8Yw=="
# JWT_EXPIRE = "7d"
# NODE_ENV = "production"
# REGION = "us"
# CLIENT_URL = "https://your-domain.com"

[build]
command = "cd frontend && npm install && npm run build"

# For Pages deployment
pages_build_output_dir = "frontend/build"

[[routes]]
pattern = "portal.qially.com/api/*"
zone_name = "qially.com"
