name = "qieos-api"
main = "src/index.ts"
compatibility_date = "2025-09-10"
node_compat = true

[vars]
JWT_ISSUER = "qieos"

[observability]
enabled = true
head_sampling_rate = 1

# set with: wrangler secret put SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY
