name = "clientportal-api"
main = "src/index.ts"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_ISSUER = "clientportal"

[observability]
enabled = true
head_sampling_rate = 1

# Build configuration
[build]
command = "npm run build:worker"
cwd = "."

# set with: wrangler secret put SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY
